Importing Modules

In [1]:
from pyexpat import features

import pandas as pd
import numpy as np
import scipy
import seaborn as sns
import matplotlib.pyplot as plt
from chart_studio.utils import pandas
%matplotlib inline

import datetime

import chart_studio.plotly as py
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go
import plotly.io as pio
import colorlover as cl
from scipy.stats import ttest_ind, pearsonr, linregress
from scipy.optimize import curve_fit
import kaleido
import os as os

from sklearn.metrics import r2_score 

from statsmodels.formula.api import ols
from statsmodels.stats.anova import anova_lm

import math as math
import cpi as cpi

In [2]:
def LinRegress(X, Y):
    data = pd.DataFrame({'x':X, 'y': Y})
    model = ols("y ~ x", data).fit()
    return model

def exponenial_func(x, a, b, c):
    return a*np.exp(-b*x)+c

def linear_func(x, b,m):
    return (m*x)+b

In [3]:
####     COLOR VALUES     ####

red = 'rgb(128, 0, 0)'
light_red = 'rgb(255, 153, 153)'

blue = 'rgb(0, 0, 128)'
light_blue = 'rgb(135,206,235)'

green = 'rgb(0, 128, 0)'

yellow = 'rgb(255,165,0)'

gray = 'rgb(201,201,201)'

Reading data

In [4]:
df = pd.read_csv('CSV/Mean House Prices/MSPUS.csv')

copy = df.copy() # backup of dataset

df.isna().info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 246 entries, 0 to 245
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   DATE    246 non-null    bool
 1   MSPUS   246 non-null    bool
dtypes: bool(2)
memory usage: 624.0 bytes

In [5]:
df.head()

         DATE    MSPUS
0  1963-01-01  17800.0
1  1963-04-01  18000.0
2  1963-07-01  17900.0
3  1963-10-01  18500.0
4  1964-01-01  18500.0

section 1 :D

In [6]:
df.dropna(axis = 0, inplace = True) # delete all rows that have N/A values

df1 = df.copy()

df1['year'] = pd.to_datetime(df1['DATE']).dt.year

# year_avg = df1.groupby('year')[['MSPUS']].mean().reset_index()

df1 = df1[df1["year"] != 2024]
df1.tail()

           DATE     MSPUS  year
239  2022-10-01  442600.0  2022
240  2023-01-01  429000.0  2023
241  2023-04-01  418500.0  2023
242  2023-07-01  435400.0  2023
243  2023-10-01  423200.0  2023

In [7]:
df1["year"] = pd.to_numeric(df1["year"], errors="coerce").astype("Int64")

In [8]:
df1["real_dollars"] = df1.apply(lambda x: cpi.inflate(x["MSPUS"], int(x["year"])), axis=1)

In [9]:
df1.tail()

           DATE     MSPUS  year   real_dollars
239  2022-10-01  442600.0  2022  460819.412619
240  2023-01-01  429000.0  2023  429000.000000
241  2023-04-01  418500.0  2023  418500.000000
242  2023-07-01  435400.0  2023  435400.000000
243  2023-10-01  423200.0  2023  423200.000000

In [10]:
reg_df = df1.copy()

reg_df['item_id'] = reg_df.index



reg_df

           DATE     MSPUS  year   real_dollars  item_id
0    1963-01-01   17800.0  1963  177244.954248        0
1    1963-04-01   18000.0  1963  179236.470588        1
2    1963-07-01   17900.0  1963  178240.712418        2
3    1963-10-01   18500.0  1963  184215.261438        3
4    1964-01-01   18500.0  1964  181838.290323        4
..          ...       ...   ...            ...      ...
239  2022-10-01  442600.0  2022  460819.412619      239
240  2023-01-01  429000.0  2023  429000.000000      240
241  2023-04-01  418500.0  2023  418500.000000      241
242  2023-07-01  435400.0  2023  435400.000000      242
243  2023-10-01  423200.0  2023  423200.000000      243

[244 rows x 5 columns]

In [11]:
fig = go.Figure()
fig.update_layout(title="Temporal House Price Over Quarters: 1963 - 2023", title_font_size = 30,
                  font=dict( family="Courier New, monospace", size=25,color="#000000"),
                  template = "ggplot2", hovermode= 'closest', legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01))
fig.update_xaxes(showline=True, linewidth=2, linecolor='gray', title='Time (Quarters)')
fig.update_yaxes(showline=True, linewidth=2, linecolor='gray', title='House Price (USD)')

fig.add_trace(go.Scatter(x = df['DATE'], y = df1['real_dollars'], mode = 'lines',
                         name = 'House Price', line=dict(color=red, width=4)))

####     REGRESSION     ####

X = pd.DataFrame(reg_df[reg_df['item_id'].between(0,148)][['item_id']])
y = pd.DataFrame(reg_df[reg_df['item_id'].between(0,148)][['real_dollars']])
model = LinRegress(X['item_id'], y['real_dollars'])
yy= linear_func(X, *model._results.params)


fig.add_trace(go.Scatter(x = pd.DataFrame(reg_df[reg_df['item_id'].between(0,148)][['DATE']])['DATE'], y = yy['item_id'], mode = 'lines',
                          name = 'Pre-2000 Regression', 
                          line=dict(dash='dash', width=3),marker_color=light_red))

####     REGRESSION     ####

X = pd.DataFrame(reg_df[reg_df['item_id'].between(148,245)][['item_id']])
y = pd.DataFrame(reg_df[reg_df['item_id'].between(148,245)][['real_dollars']])
model = LinRegress(X['item_id'], y['real_dollars'])
yy= linear_func(X, *model._results.params)

fig.add_trace(go.Scatter(x = pd.DataFrame(reg_df[reg_df['item_id'].between(148,245)][['DATE']])['DATE'], y = yy['item_id'], mode = 'lines',
                         name = 'Post-2000 Regression', 
                         line=dict(dash='dash', width=3), marker_color=light_blue))


####     SPLIT LINE     ####

fig.add_trace(go.Scatter( x=['2000-01-01', '2000-01-01'], y=[0, 450000], mode="lines",line=dict(color="gray", width=3), showlegend=False))

pio.write_image(fig, f"images/fig1.png", width=5*300, height=2*300, scale=1.5)

fig

In [12]:
####     PRE 2000     ####

X = pd.DataFrame(reg_df[reg_df['item_id'].between(0,148)][['item_id']])
y = pd.DataFrame(reg_df[reg_df['item_id'].between(0,148)][['real_dollars']])

model = LinRegress(X['item_id'], y['real_dollars'])

b,m = model._results.params
r = model.rsquared
t = model._results.tvalues[1]

print("Pre-2000 Regression:")
print(f"y = {m}*x+{b}")
print(f"R² = {r}")
print(f"t = {t}")

####     POST 2000     ####

X = pd.DataFrame(reg_df[reg_df['item_id'].between(148,245)][['item_id']])
y = pd.DataFrame(reg_df[reg_df['item_id'].between(148,245)][['real_dollars']])

model = LinRegress(X['item_id'], y['real_dollars'])

b,m = model._results.params
r = model.rsquared
t = model._results.tvalues[1]

print("Post-2000 Regression:")
print(f"y = {m}*x+{b}")
print(f"R² = {r}")
print(f"t = {t}")

Pre-2000 Regression:
y = 706.691994160255*x+188823.39726498755
R² = 0.7807180356538315
t = 22.87727627979921
Post-2000 Regression:
y = 1281.3831579788052*x+107874.62869576333
R² = 0.6334911957276381
t = 12.746531179686745

In [13]:
index = len(reg_df.index)
index -= 1
d = reg_df.copy()
d['DATE'] = pd.to_datetime(d['DATE'])
d.real_dollars = d.groupby(d.DATE.dt.year)['real_dollars'].transform('mean')

d=d.iloc[::4]
d=d.reset_index()
d.drop(['index', 'item_id'], axis=1, inplace=True)


d.real_dollars = d.real_dollars.pct_change()

d=d.drop(0, axis=0)

d.real_dollars *= 100

d

         DATE     MSPUS  year  real_dollars
1  1964-01-01   18500.0  1964      3.494773
2  1965-01-01   20200.0  1965      4.652870
3  1966-01-01   21000.0  1966      3.864734
4  1967-01-01   22300.0  1967      2.645871
5  1968-01-01   23900.0  1968      4.625489
6  1969-01-01   25700.0  1969     -2.118309
7  1970-01-01   23900.0  1970    -13.263883
8  1971-01-01   24300.0  1971      2.944293
9  1972-01-01   26200.0  1972      5.724318
10 1973-01-01   30200.0  1973     11.502238
11 1974-01-01   35200.0  1974     -0.408168
12 1975-01-01   38100.0  1975     -0.166668
13 1976-01-01   42800.0  1976      6.468628
14 1977-01-01   46300.0  1977      3.819913
15 1978-01-01   53000.0  1978      6.154729
16 1979-01-01   60600.0  1979      0.902407
17 1980-01-01   63700.0  1980     -9.085019
18 1981-01-01   66800.0  1981     -3.470996
19 1982-01-01   66400.0  1982     -5.427414
20 1983-01-01   73300.0  1983      5.495112
21 1984-01-01   78200.0  1984      1.679859
22 1985-01-01   82800.0  1985      1.784950
23 1986-01-01   88000.0  1986      7.203455
24 1987-01-01   97900.0  1987      9.767324
25 1988-01-01  110000.0  1988      2.928707
26 1989-01-01  118000.0  1989      2.374101
27 1990-01-01  123900.0  1990     -3.649073
28 1991-01-01  120000.0  1991     -5.862474
29 1992-01-01  119500.0  1992     -1.789500
30 1993-01-01  125000.0  1993      1.193148
31 1994-01-01  130000.0  1994      0.528676
32 1995-01-01  130000.0  1995     -0.481844
33 1996-01-01  137000.0  1996      2.062209
34 1997-01-01  145000.0  1997      1.067853
35 1998-01-01  152200.0  1998      3.168870
36 1999-01-01  157400.0  1999      3.119905
37 2000-01-01  165300.0  2000      1.234173
38 2001-01-01  169800.0  2001      0.453997
39 2002-01-01  188700.0  2002      5.794147
40 2003-01-01  186000.0  2003      0.977801
41 2004-01-01  212700.0  2004     10.600528
42 2005-01-01  232500.0  2005      4.881152
43 2006-01-01  247700.0  2006     -0.176363
44 2007-01-01  257400.0  2007     -2.290664
45 2008-01-01  233900.0  2008     -9.752110
46 2009-01-01  208400.0  2009     -5.719898
47 2010-01-01  222900.0  2010      1.602622
48 2011-01-01  226900.0  2011     -2.102293
49 2012-01-01  238400.0  2012      6.467234
50 2013-01-01  258400.0  2013      7.357503
51 2014-01-01  275200.0  2014      5.629897
52 2015-01-01  289200.0  2015      2.808596
53 2016-01-01  299800.0  2016      2.438811
54 2017-01-01  313100.0  2017      3.465623
55 2018-01-01  331800.0  2018     -1.521391
56 2019-01-01  313000.0  2019     -3.297081
57 2020-01-01  329000.0  2020      1.218111
58 2021-01-01  355000.0  2021     11.477670
59 2022-01-01  413500.0  2022      4.665664
60 2023-01-01  429000.0  2023     -5.379031

In [14]:
fig = go.Figure()
fig.update_layout(title="Percent Change in House Price YoY: 1963 - 2023", title_font_size = 30,
                  font=dict( family="Courier New, monospace", size=25,color="#000000"),
                  template = "ggplot2", hovermode= 'closest', legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01))
fig.update_xaxes(showline=True, linewidth=2, linecolor='gray', title='Time (Years)')
fig.update_yaxes(range = [-15,20],showline=True, linewidth=2, linecolor='gray', title='Percent Change')

fig.add_trace(go.Scatter(x = d['DATE'], y = d['real_dollars'], mode = 'lines',
                         name = 'House Price', fill='tonexty', line=dict(color=red, width=4)))

####     SPLIT LINE     ####

fig.add_trace(go.Scatter( x=['2000-01-01', '2000-01-01'], y=[-14.75, 19.75], mode="lines",line=dict(color="#000000", width=3), showlegend=False))

pio.write_image(fig, f"images/fig2.png", width=5*300, height=2*300, scale=1.5)
fig

In [15]:
df = pd.read_csv('CSV/Zillow Data/for-sale inventory/Metro_invt_fs_uc_sfrcondo_month.csv')

df = df.iloc[:1] # Select only US
df = df.drop(['RegionID', 'SizeRank', 'RegionType', 'StateName'], axis=1) # Drop irrelevant columns
df = df.T # Flip it so it's not horizontal
df = df.iloc[1:] # remove top column stuff
df = df.reset_index()
df = df.set_axis(['DATE', 'INVENTORY_COUNT'], axis = 1)

for_sale = df
for_sale

          DATE INVENTORY_COUNT
0   2018-01-31       1360757.0
1   2018-02-28       1388126.0
2   2018-03-31       1515701.0
3   2018-04-30       1596750.0
4   2018-05-31       1664788.0
..         ...             ...
75  2024-04-30       1031815.0
76  2024-05-31       1110857.0
77  2024-06-30       1160760.0
78  2024-07-31       1177375.0
79  2024-08-31       1179692.0

[80 rows x 2 columns]

In [18]:
df = pd.read_csv('CSV/Zillow Data/sales count/Metro_sales_count_now_uc_sfrcondo_month.csv')


df=df.iloc[:1] # Select only US
df = df.drop(['RegionID', 'SizeRank', 'RegionType', 'StateName'], axis=1) # Drop irrelevant columns
df = df.T # Flip it so it's not horizontal
df = df.iloc[1:] # remove top column stuff
df['Index'] = range(1, len(df)+1)

df = df.loc[df['Index'] >= 120] # hardcode
df = df.drop(['Index'], axis=1)
df = df.reset_index()

df = df.set_axis(['DATE', 'SALE_COUNT'], axis = 1)

sale_count = df
sale_count

          DATE SALE_COUNT
0   2018-01-31   280933.0
1   2018-02-28   278908.0
2   2018-03-31   380147.0
3   2018-04-30   401495.0
4   2018-05-31   463931.0
..         ...        ...
75  2024-04-30   318615.0
76  2024-05-31   350767.0
77  2024-06-30   326229.0
78  2024-07-31   340368.0
79  2024-08-31   332735.0

[80 rows x 2 columns]

In [20]:
fig = go.Figure()
fig.update_layout(title="Housing Sale and Inventory Count over Time: 2018 - 2024", title_font_size = 30,
                  font=dict( family="Courier New, monospace", size=25,color="#000000"),
                  template = "ggplot2", hovermode= 'closest', legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01))
fig.update_xaxes(showline=True, linewidth=2, linecolor='gray', title="Time (Months)")
fig.update_yaxes(showline=True, linewidth=2, linecolor='gray', title="Count")

fig.add_trace(go.Scatter(x = sale_count['DATE'], y = sale_count['SALE_COUNT'], mode = 'lines',
                         name = 'Sale Count', line=dict(color=red, width=4)))

fig.add_trace(go.Scatter(x = for_sale['DATE'], y = for_sale['INVENTORY_COUNT'], mode = 'lines',
                         name = 'Inventory Count', line=dict(color=light_blue, width=4)))

pio.write_image(fig, "images/fig3.png", width=5*300, height=2*300, scale=1.5)

fig

In [21]:
df = pd.read_csv('CSV/Zillow Data/days to pend/Metro_mean_doz_pending_uc_sfrcondo_sm_month.csv')

df = df.iloc[:1] # Select only US
df = df.drop(['RegionID', 'SizeRank', 'RegionType', 'StateName'], axis=1) # Drop irrelevant columns

df = df.T # Flip it so it's not horizontal

df = df.iloc[1:] # remove top column stuff

df = df.reset_index()

df = df.set_axis(['DATE', 'DAYS_TO_CLOSE'], axis = 1)

df['item_id'] = df.index
df['DAYS_TO_CLOSE'] = df['DAYS_TO_CLOSE'].astype(int)
time_to_close = df
time_to_close

          DATE  DAYS_TO_CLOSE  item_id
0   2018-03-31             51        0
1   2018-04-30             48        1
2   2018-05-31             45        2
3   2018-06-30             43        3
4   2018-07-31             44        4
..         ...            ...      ...
76  2024-07-31             38       76
77  2024-08-31             41       77
78  2024-09-30             44       78
79  2024-10-31             46       79
80  2024-11-30             50       80

[81 rows x 3 columns]

In [22]:
time_to_close.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81 entries, 0 to 80
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   DATE           81 non-null     object
 1   DAYS_TO_CLOSE  81 non-null     int64
 2   item_id        81 non-null     int64
dtypes: int64(2), object(1)
memory usage: 2.0+ KB

In [23]:
fig = go.Figure()
fig.update_layout(title="Average Days on Market Versus Time: 2018 - 2024", title_font_size = 30,
                  font=dict( family="Courier New, monospace", size=25,color="#000000"),
                  template = "ggplot2", hovermode= 'closest', legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01))
fig.update_xaxes(showline=True, linewidth=2, linecolor='gray', title="Time (Months)")
fig.update_yaxes(showline=True, linewidth=2, linecolor='gray', title="Days To Pending")

fig.add_trace(go.Scatter(x = time_to_close['DATE'], y = time_to_close['DAYS_TO_CLOSE'], mode = 'lines',
                         name = 'Days To Pending', line=dict(color=red, width=4), showlegend=True))

####     REGRESSION     ####

X = time_to_close['item_id']
y = time_to_close['DAYS_TO_CLOSE']
model = LinRegress(X, y)
yy= linear_func(X, *model._results.params)


fig.add_trace(go.Scatter(x = time_to_close['DATE'], y = yy, mode = 'lines',
                          name = 'Regression',
                          line=dict(dash='dash', width=3),marker_color=light_red))

####     REGRESSION     ####

# X = pd.DataFrame(reg_df[reg_df['item_id'].between(148,245)][['item_id']])
# y = pd.DataFrame(reg_df[reg_df['item_id'].between(148,245)][['MSPUS']])
# model = LinRegress(X['item_id'], y['MSPUS'])
# yy= linear_func(X, *model._results.params)
#
# fig.add_trace(go.Scatter(x = pd.DataFrame(reg_df[reg_df['item_id'].between(148,245)][['DATE']])['DATE'], y = yy['item_id'], mode = 'lines',
#                          name = 'Post-2000 Regression',
#                          line=dict(dash='dash', width=3), marker_color=light_blue))


####     SPLIT LINE     ####

# fig.add_trace(go.Scatter( x=['2000-01-01', '2000-01-01'], y=[0, 450000], mode="lines",line=dict(color="gray", width=3), showlegend=False))

pio.write_image(fig, "images/fig4.png", width=5*300, height=2*300, scale=1.5)

fig

In [24]:
X = time_to_close['item_id']
y = time_to_close['DAYS_TO_CLOSE']
model = LinRegress(X, y)
yy= linear_func(X, *model._results.params)


b,m = model._results.params
r = model.rsquared
t = model._results.tvalues[1]

print("Average Time on Market:")
print(f"y = {m}*x+{b}")
print(f"R² = {r}")
print(f"t = {t}")

Average Time on Market:
y = -0.29006323396567246*x+55.849442938873835
R² = 0.24710200463254894
t = -5.091943892505221

In [25]:
# First time with geographic data in P.IO

# TODO: Return to cleanup code

# import US counties as FIPS
from urllib.request import urlopen
import json
with urlopen('https://raw.githubusercontent.com/PublicaMundi/MappingAPI/refs/heads/master/data/geojson/us-states.json') as response:
    states = json.load(response)

states["features"][0]

{'type': 'Feature',
 'id': '01',
 'properties': {'name': 'Alabama', 'density': 94.65},
 'geometry': {'type': 'Polygon',
  'coordinates': [[[-87.359296, 35.00118],
    [-85.606675, 34.984749],
    [-85.431413, 34.124869],
    [-85.184951, 32.859696],
    [-85.069935, 32.580372],
    [-84.960397, 32.421541],
    [-85.004212, 32.322956],
    [-84.889196, 32.262709],
    [-85.058981, 32.13674],
    [-85.053504, 32.01077],
    [-85.141136, 31.840985],
    [-85.042551, 31.539753],
    [-85.113751, 31.27686],
    [-85.004212, 31.003013],
    [-85.497137, 30.997536],
    [-87.600282, 30.997536],
    [-87.633143, 30.86609],
    [-87.408589, 30.674397],
    [-87.446927, 30.510088],
    [-87.37025, 30.427934],
    [-87.518128, 30.280057],
    [-87.655051, 30.247195],
    [-87.90699, 30.411504],
    [-87.934375, 30.657966],
    [-88.011052, 30.685351],
    [-88.10416, 30.499135],
    [-88.137022, 30.318396],
    [-88.394438, 30.367688],
    [-88.471115, 31.895754],
    [-88.241084, 33.796253],
    [-88.098683, 34.891641],
    [-88.202745, 34.995703],
    [-87.359296, 35.00118]]]}}

In [26]:
df = pd.read_csv('CSV/House Price Geography/State/PriceByState.csv')
df['fips'] = df['fips'].astype(str)
df['fips'] = df['fips'].apply(lambda x: f"0{x}" if len(x)<2 else x)
# df['VALUE'] = pd.to_numeric(df['VALUE'], errors='coerce')
df.head()

  fips   VALUE
0   01  277000
1   02  396000
2   04  462000
3   05  260000
4   06  869000

In [27]:
fig = px.choropleth(df, geojson=states, locations='fips', color='VALUE',
                           color_continuous_scale="orrd",
                           range_color=(150000, 947000),
                           scope="usa",
                           labels={'VALUE':'Avg. Price'}
                          )
fig.update_layout(title="Average House Price Per State (Oct. 2024)", title_font_size = 30,
                  font=dict( family="Courier New, monospace", size=25,color="#000000"),
                  template = "ggplot2", hovermode= 'closest', legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01), margin=dict(l=0, r=0, b=0, t=50, pad=0))
pio.write_image(fig, "images/whole_us.png", width=5*300, height=2*300, scale=1.5)
fig

In [28]:
states["features"][42]

{'type': 'Feature',
 'id': '47',
 'properties': {'name': 'Tennessee', 'density': 88.08},
 'geometry': {'type': 'Polygon',
  'coordinates': [[[-88.054868, 36.496384],
    [-88.071299, 36.677123],
    [-87.852221, 36.633308],
    [-86.592525, 36.655216],
    [-85.486183, 36.616877],
    [-85.289013, 36.627831],
    [-84.544149, 36.594969],
    [-83.689746, 36.584015],
    [-83.673316, 36.600446],
    [-81.679709, 36.589492],
    [-81.723525, 36.353984],
    [-81.909741, 36.304691],
    [-82.03571, 36.118475],
    [-82.216449, 36.156814],
    [-82.610789, 35.965121],
    [-82.638174, 36.063706],
    [-82.775097, 35.997983],
    [-82.994175, 35.773428],
    [-83.251591, 35.718659],
    [-83.498053, 35.565304],
    [-83.7719, 35.559827],
    [-84.018363, 35.41195],
    [-84.09504, 35.247642],
    [-84.29221, 35.225734],
    [-84.319594, 34.990226],
    [-85.606675, 34.984749],
    [-87.359296, 35.00118],
    [-88.202745, 34.995703],
    [-88.471115, 34.995703],
    [-90.311367, 34.995703],
    [-90.212782, 35.023087],
    [-90.114197, 35.198349],
    [-90.130628, 35.439335],
    [-89.944412, 35.603643],
    [-89.911551, 35.756997],
    [-89.763673, 35.811767],
    [-89.730812, 35.997983],
    [-89.533642, 36.249922],
    [-89.539119, 36.496384],
    [-89.484349, 36.496384],
    [-89.418626, 36.496384],
    [-89.298133, 36.507338],
    [-88.054868, 36.496384]]]}}

In [29]:
state_names = ["Connecticut", "Maine", "Massachusetts", "New Hampshire", "Rhode Island", "Vermont", "New Jersey", "New York", "Pennsylvania", "Delaware", "Maryland"]

northeast = [
    feature for feature in states["features"]
    if feature["properties"]["name"] in state_names
]

northeastgeoj = {
    "type": "FeatureCollection",
    "features": northeast
}

northeastgeoj["features"][0]

{'type': 'Feature',
 'id': '09',
 'properties': {'name': 'Connecticut', 'density': 739.1},
 'geometry': {'type': 'Polygon',
  'coordinates': [[[-73.053528, 42.039048],
    [-71.799309, 42.022617],
    [-71.799309, 42.006186],
    [-71.799309, 41.414677],
    [-71.859555, 41.321569],
    [-71.947186, 41.338],
    [-72.385341, 41.261322],
    [-72.905651, 41.28323],
    [-73.130205, 41.146307],
    [-73.371191, 41.102491],
    [-73.655992, 40.987475],
    [-73.727192, 41.102491],
    [-73.48073, 41.21203],
    [-73.55193, 41.294184],
    [-73.486206, 42.050002],
    [-73.053528, 42.039048]]]}}

In [30]:
fig = px.choropleth(df, geojson=northeastgeoj, locations='fips', color='VALUE',
                           color_continuous_scale="orrd",
                           range_color=(319000, 646000),
                           scope="usa",
                           labels={'VALUE':'Avg. Price'}
                          )
fig.update_layout(title="Average House Price In The Northeast US (Oct. 2024)", title_font_size = 30,
                  font=dict( family="Courier New, monospace", size=25,color="#000000"),
                  template = "ggplot2", hovermode= 'closest', legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01), margin=dict(l=0, r=0, b=0, t=50, pad=0))
fig.update_geos(fitbounds="locations")
pio.write_image(fig, "images/northeast.png", width=5*300, height=2*300, scale=1.5)
fig.show()

In [31]:
state_names = ["Illinois", "Indiana", "Iowa", "Kansas", "Michigan", "Minnesota", "Missouri", "Nebraska", "North Dakota", "Ohio", "South Dakota", "Wisconsin"]

midwest = [
    feature for feature in states["features"]
    if feature["properties"]["name"] in state_names
]

midwestgeoj = {
    "type": "FeatureCollection",
    "features": midwest
}

In [32]:
fig = px.choropleth(df, geojson=midwestgeoj, locations='fips', color='VALUE',
                           color_continuous_scale="orrd",
                           range_color=(241000, 364000),
                           scope="usa",
                           labels={'VALUE':'Avg. Price'}
                          )
fig.update_layout(title="Average House Price In The Midwest US (Oct. 2024)", title_font_size = 30,
                  font=dict( family="Courier New, monospace", size=25,color="#000000"),
                  template = "ggplot2", hovermode= 'closest', legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01), margin=dict(l=0, r=0, b=0, t=50, pad=0))
fig.update_geos(fitbounds="locations")
pio.write_image(fig, "images/midwest.png", width=5*300, height=2*300, scale=1.5)
fig

In [33]:
state_names = ["Alabama", "Arkansas", "Florida", "Georgia", "Kentucky", "Louisiana", "Mississippi", "North Carolina", "Oklahoma", "South Carolina", "Tennessee", "Texas", "Virginia", "West Virginia"]

south = [
    feature for feature in states["features"]
    if feature["properties"]["name"] in state_names
]

southgeoj = {
    "type": "FeatureCollection",
    "features": south
}

In [34]:
fig = px.choropleth(df, geojson=southgeoj, locations='fips', color='VALUE',
                    color_continuous_scale="orrd",
                    range_color=(247000, 433000),
                    scope="usa",
                    labels={'VALUE':'Avg. Price'}
                    )
fig.update_layout(title="Average House Price In The Southern US (Oct. 2024)", title_font_size = 30,
                  font=dict( family="Courier New, monospace", size=25,color="#000000"),
                  template = "ggplot2", hovermode= 'closest', legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01), margin=dict(l=0, r=0, b=0, t=50, pad=0))
fig.update_geos(fitbounds="locations")
pio.write_image(fig, "images/south.png", width=5*300, height=2*300, scale=1.5)
fig.show()

In [35]:
state_names = ["Arizona", "California", "Colorado", "Idaho", "Montana", "Nevada", "New Mexico", "Oregon", "Utah", "Washington", "Wyoming"]

west = [
    feature for feature in states["features"]
    if feature["properties"]["name"] in state_names
]

westgeoj = {
    "type": "FeatureCollection",
    "features": west
}

In [36]:
westgeoj

{'type': 'FeatureCollection',
 'features': [{'type': 'Feature',
   'id': '04',
   'properties': {'name': 'Arizona', 'density': 57.05},
   'geometry': {'type': 'Polygon',
    'coordinates': [[[-109.042503, 37.000263],
      [-109.04798, 31.331629],
      [-111.074448, 31.331629],
      [-112.246513, 31.704061],
      [-114.815198, 32.492741],
      [-114.72209, 32.717295],
      [-114.524921, 32.755634],
      [-114.470151, 32.843265],
      [-114.524921, 33.029481],
      [-114.661844, 33.034958],
      [-114.727567, 33.40739],
      [-114.524921, 33.54979],
      [-114.497536, 33.697668],
      [-114.535874, 33.933176],
      [-114.415382, 34.108438],
      [-114.256551, 34.174162],
      [-114.136058, 34.305608],
      [-114.333228, 34.448009],
      [-114.470151, 34.710902],
      [-114.634459, 34.87521],
      [-114.634459, 35.00118],
      [-114.574213, 35.138103],
      [-114.596121, 35.324319],
      [-114.678275, 35.516012],
      [-114.738521, 36.102045],
      [-114.371566, 36.140383],
      [-114.251074, 36.01989],
      [-114.152489, 36.025367],
      [-114.048427, 36.195153],
      [-114.048427, 37.000263],
      [-110.499369, 37.00574],
      [-109.042503, 37.000263]]]}},
  {'type': 'Feature',
   'id': '06',
   'properties': {'name': 'California', 'density': 241.7},
   'geometry': {'type': 'Polygon',
    'coordinates': [[[-123.233256, 42.006186],
      [-122.378853, 42.011663],
      [-121.037003, 41.995232],
      [-120.001861, 41.995232],
      [-119.996384, 40.264519],
      [-120.001861, 38.999346],
      [-118.71478, 38.101128],
      [-117.498899, 37.21934],
      [-116.540435, 36.501861],
      [-115.85034, 35.970598],
      [-114.634459, 35.00118],
      [-114.634459, 34.87521],
      [-114.470151, 34.710902],
      [-114.333228, 34.448009],
      [-114.136058, 34.305608],
      [-114.256551, 34.174162],
      [-114.415382, 34.108438],
      [-114.535874, 33.933176],
      [-114.497536, 33.697668],
      [-114.524921, 33.54979],
      [-114.727567, 33.40739],
      [-114.661844, 33.034958],
      [-114.524921, 33.029481],
      [-114.470151, 32.843265],
      [-114.524921, 32.755634],
      [-114.72209, 32.717295],
      [-116.04751, 32.624187],
      [-117.126467, 32.536556],
      [-117.24696, 32.668003],
      [-117.252437, 32.876127],
      [-117.329114, 33.122589],
      [-117.471515, 33.297851],
      [-117.7837, 33.538836],
      [-118.183517, 33.763391],
      [-118.260194, 33.703145],
      [-118.413548, 33.741483],
      [-118.391641, 33.840068],
      [-118.566903, 34.042715],
      [-118.802411, 33.998899],
      [-119.218659, 34.146777],
      [-119.278905, 34.26727],
      [-119.558229, 34.415147],
      [-119.875891, 34.40967],
      [-120.138784, 34.475393],
      [-120.472878, 34.448009],
      [-120.64814, 34.579455],
      [-120.609801, 34.858779],
      [-120.670048, 34.902595],
      [-120.631709, 35.099764],
      [-120.894602, 35.247642],
      [-120.905556, 35.450289],
      [-121.004141, 35.461243],
      [-121.168449, 35.636505],
      [-121.283465, 35.674843],
      [-121.332757, 35.784382],
      [-121.716143, 36.195153],
      [-121.896882, 36.315645],
      [-121.935221, 36.638785],
      [-121.858544, 36.6114],
      [-121.787344, 36.803093],
      [-121.929744, 36.978355],
      [-122.105006, 36.956447],
      [-122.335038, 37.115279],
      [-122.417192, 37.241248],
      [-122.400761, 37.361741],
      [-122.515777, 37.520572],
      [-122.515777, 37.783465],
      [-122.329561, 37.783465],
      [-122.406238, 38.15042],
      [-122.488392, 38.112082],
      [-122.504823, 37.931343],
      [-122.701993, 37.893004],
      [-122.937501, 38.029928],
      [-122.97584, 38.265436],
      [-123.129194, 38.451652],
      [-123.331841, 38.566668],
      [-123.44138, 38.698114],
      [-123.737134, 38.95553],
      [-123.687842, 39.032208],
      [-123.824765, 39.366301],
      [-123.764519, 39.552517],
      [-123.85215, 39.831841],
      [-124.109566, 40.105688],
      [-124.361506, 40.259042],
      [-124.410798, 40.439781],
      [-124.158859, 40.877937],
      [-124.109566, 41.025814],
      [-124.158859, 41.14083],
      [-124.065751, 41.442061],
      [-124.147905, 41.715908],
      [-124.257444, 41.781632],
      [-124.213628, 42.000709],
      [-123.233256, 42.006186]]]}},
  {'type': 'Feature',
   'id': '08',
   'properties': {'name': 'Colorado', 'density': 49.33},
   'geometry': {'type': 'Polygon',
    'coordinates': [[[-107.919731, 41.003906],
      [-105.728954, 40.998429],
      [-104.053011, 41.003906],
      [-102.053927, 41.003906],
      [-102.053927, 40.001626],
      [-102.042974, 36.994786],
      [-103.001438, 37.000263],
      [-104.337812, 36.994786],
      [-106.868158, 36.994786],
      [-107.421329, 37.000263],
      [-109.042503, 37.000263],
      [-109.042503, 38.166851],
      [-109.058934, 38.27639],
      [-109.053457, 39.125316],
      [-109.04798, 40.998429],
      [-107.919731, 41.003906]]]}},
  {'type': 'Feature',
   'id': '16',
   'properties': {'name': 'Idaho', 'density': 19.15},
   'geometry': {'type': 'Polygon',
    'coordinates': [[[-116.04751, 49.000239],
      [-116.04751, 47.976051],
      [-115.724371, 47.696727],
      [-115.718894, 47.42288],
      [-115.527201, 47.302388],
      [-115.324554, 47.258572],
      [-115.302646, 47.187372],
      [-114.930214, 46.919002],
      [-114.886399, 46.809463],
      [-114.623506, 46.705401],
      [-114.612552, 46.639678],
      [-114.322274, 46.645155],
      [-114.464674, 46.272723],
      [-114.492059, 46.037214],
      [-114.387997, 45.88386],
      [-114.568736, 45.774321],
      [-114.497536, 45.670259],
      [-114.546828, 45.560721],
      [-114.333228, 45.456659],
      [-114.086765, 45.593582],
      [-113.98818, 45.703121],
      [-113.807441, 45.604536],
      [-113.834826, 45.522382],
      [-113.736241, 45.330689],
      [-113.571933, 45.128042],
      [-113.45144, 45.056842],
      [-113.456917, 44.865149],
      [-113.341901, 44.782995],
      [-113.133778, 44.772041],
      [-113.002331, 44.448902],
      [-112.887315, 44.394132],
      [-112.783254, 44.48724],
      [-112.471068, 44.481763],
      [-112.241036, 44.569394],
      [-112.104113, 44.520102],
      [-111.868605, 44.563917],
      [-111.819312, 44.509148],
      [-111.616665, 44.547487],
      [-111.386634, 44.75561],
      [-111.227803, 44.580348],
      [-111.047063, 44.476286],
      [-111.047063, 42.000709],
      [-112.164359, 41.995232],
      [-114.04295, 41.995232],
      [-117.027882, 42.000709],
      [-117.027882, 43.830007],
      [-116.896436, 44.158624],
      [-116.97859, 44.240778],
      [-117.170283, 44.257209],
      [-117.241483, 44.394132],
      [-117.038836, 44.750133],
      [-116.934774, 44.782995],
      [-116.830713, 44.930872],
      [-116.847143, 45.02398],
      [-116.732128, 45.144473],
      [-116.671881, 45.319735],
      [-116.463758, 45.61549],
      [-116.545912, 45.752413],
      [-116.78142, 45.823614],
      [-116.918344, 45.993399],
      [-116.92382, 46.168661],
      [-117.055267, 46.343923],
      [-117.038836, 46.426077],
      [-117.044313, 47.762451],
      [-117.033359, 49.000239],
      [-116.04751, 49.000239]]]}},
  {'type': 'Feature',
   'id': '30',
   'properties': {'name': 'Montana', 'density': 6.858},
   'geometry': {'type': 'Polygon',
    'coordinates': [[[-104.047534, 49.000239],
      [-104.042057, 47.861036],
      [-104.047534, 45.944106],
      [-104.042057, 44.996596],
      [-104.058488, 44.996596],
      [-105.91517, 45.002073],
      [-109.080842, 45.002073],
      [-111.05254, 45.002073],
      [-111.047063, 44.476286],
      [-111.227803, 44.580348],
      [-111.386634, 44.75561],
      [-111.616665, 44.547487],
      [-111.819312, 44.509148],
      [-111.868605, 44.563917],
      [-112.104113, 44.520102],
      [-112.241036, 44.569394],
      [-112.471068, 44.481763],
      [-112.783254, 44.48724],
      [-112.887315, 44.394132],
      [-113.002331, 44.448902],
      [-113.133778, 44.772041],
      [-113.341901, 44.782995],
      [-113.456917, 44.865149],
      [-113.45144, 45.056842],
      [-113.571933, 45.128042],
      [-113.736241, 45.330689],
      [-113.834826, 45.522382],
      [-113.807441, 45.604536],
      [-113.98818, 45.703121],
      [-114.086765, 45.593582],
      [-114.333228, 45.456659],
      [-114.546828, 45.560721],
      [-114.497536, 45.670259],
      [-114.568736, 45.774321],
      [-114.387997, 45.88386],
      [-114.492059, 46.037214],
      [-114.464674, 46.272723],
      [-114.322274, 46.645155],
      [-114.612552, 46.639678],
      [-114.623506, 46.705401],
      [-114.886399, 46.809463],
      [-114.930214, 46.919002],
      [-115.302646, 47.187372],
      [-115.324554, 47.258572],
      [-115.527201, 47.302388],
      [-115.718894, 47.42288],
      [-115.724371, 47.696727],
      [-116.04751, 47.976051],
      [-116.04751, 49.000239],
      [-111.50165, 48.994762],
      [-109.453274, 49.000239],
      [-104.047534, 49.000239]]]}},
  {'type': 'Feature',
   'id': '32',
   'properties': {'name': 'Nevada', 'density': 24.8},
   'geometry': {'type': 'Polygon',
    'coordinates': [[[-117.027882, 42.000709],
      [-114.04295, 41.995232],
      [-114.048427, 37.000263],
      [-114.048427, 36.195153],
      [-114.152489, 36.025367],
      [-114.251074, 36.01989],
      [-114.371566, 36.140383],
      [-114.738521, 36.102045],
      [-114.678275, 35.516012],
      [-114.596121, 35.324319],
      [-114.574213, 35.138103],
      [-114.634459, 35.00118],
      [-115.85034, 35.970598],
      [-116.540435, 36.501861],
      [-117.498899, 37.21934],
      [-118.71478, 38.101128],
      [-120.001861, 38.999346],
      [-119.996384, 40.264519],
      [-120.001861, 41.995232],
      [-118.698349, 41.989755],
      [-117.027882, 42.000709]]]}},
  {'type': 'Feature',
   'id': '35',
   'properties': {'name': 'New Mexico', 'density': 17.16},
   'geometry': {'type': 'Polygon',
    'coordinates': [[[-107.421329, 37.000263],
      [-106.868158, 36.994786],
      [-104.337812, 36.994786],
      [-103.001438, 37.000263],
      [-103.001438, 36.501861],
      [-103.039777, 36.501861],
      [-103.045254, 34.01533],
      [-103.067161, 33.002096],
      [-103.067161, 31.999816],
      [-106.616219, 31.999816],
      [-106.643603, 31.901231],
      [-106.528588, 31.786216],
      [-108.210008, 31.786216],
      [-108.210008, 31.331629],
      [-109.04798, 31.331629],
      [-109.042503, 37.000263],
      [-107.421329, 37.000263]]]}},
  {'type': 'Feature',
   'id': '41',
   'properties': {'name': 'Oregon', 'density': 40.33},
   'geometry': {'type': 'Polygon',
    'coordinates': [[[-123.211348, 46.174138],
      [-123.11824, 46.185092],
      [-122.904639, 46.08103],
      [-122.811531, 45.960537],
      [-122.762239, 45.659305],
      [-122.247407, 45.549767],
      [-121.809251, 45.708598],
      [-121.535404, 45.725029],
      [-121.217742, 45.670259],
      [-121.18488, 45.604536],
      [-120.637186, 45.746937],
      [-120.505739, 45.697644],
      [-120.209985, 45.725029],
      [-119.963522, 45.823614],
      [-119.525367, 45.911245],
      [-119.125551, 45.933153],
      [-118.988627, 45.998876],
      [-116.918344, 45.993399],
      [-116.78142, 45.823614],
      [-116.545912, 45.752413],
      [-116.463758, 45.61549],
      [-116.671881, 45.319735],
      [-116.732128, 45.144473],
      [-116.847143, 45.02398],
      [-116.830713, 44.930872],
      [-116.934774, 44.782995],
      [-117.038836, 44.750133],
      [-117.241483, 44.394132],
      [-117.170283, 44.257209],
      [-116.97859, 44.240778],
      [-116.896436, 44.158624],
      [-117.027882, 43.830007],
      [-117.027882, 42.000709],
      [-118.698349, 41.989755],
      [-120.001861, 41.995232],
      [-121.037003, 41.995232],
      [-122.378853, 42.011663],
      [-123.233256, 42.006186],
      [-124.213628, 42.000709],
      [-124.356029, 42.115725],
      [-124.432706, 42.438865],
      [-124.416275, 42.663419],
      [-124.553198, 42.838681],
      [-124.454613, 43.002989],
      [-124.383413, 43.271359],
      [-124.235536, 43.55616],
      [-124.169813, 43.8081],
      [-124.060274, 44.657025],
      [-124.076705, 44.772041],
      [-123.97812, 45.144473],
      [-123.939781, 45.659305],
      [-123.994551, 45.944106],
      [-123.945258, 46.113892],
      [-123.545441, 46.261769],
      [-123.370179, 46.146753],
      [-123.211348, 46.174138]]]}},
  {'type': 'Feature',
   'id': '49',
   'properties': {'name': 'Utah', 'density': 34.3},
   'geometry': {'type': 'Polygon',
    'coordinates': [[[-112.164359, 41.995232],
      [-111.047063, 42.000709],
      [-111.047063, 40.998429],
      [-109.04798, 40.998429],
      [-109.053457, 39.125316],
      [-109.058934, 38.27639],
      [-109.042503, 38.166851],
      [-109.042503, 37.000263],
      [-110.499369, 37.00574],
      [-114.048427, 37.000263],
      [-114.04295, 41.995232],
      [-112.164359, 41.995232]]]}},
  {'type': 'Feature',
   'id': '53',
   'properties': {'name': 'Washington', 'density': 102.6},
   'geometry': {'type': 'MultiPolygon',
    'coordinates': [[[[-117.033359, 49.000239],
       [-117.044313, 47.762451],
       [-117.038836, 46.426077],
       [-117.055267, 46.343923],
       [-116.92382, 46.168661],
       [-116.918344, 45.993399],
       [-118.988627, 45.998876],
       [-119.125551, 45.933153],
       [-119.525367, 45.911245],
       [-119.963522, 45.823614],
       [-120.209985, 45.725029],
       [-120.505739, 45.697644],
       [-120.637186, 45.746937],
       [-121.18488, 45.604536],
       [-121.217742, 45.670259],
       [-121.535404, 45.725029],
       [-121.809251, 45.708598],
       [-122.247407, 45.549767],
       [-122.762239, 45.659305],
       [-122.811531, 45.960537],
       [-122.904639, 46.08103],
       [-123.11824, 46.185092],
       [-123.211348, 46.174138],
       [-123.370179, 46.146753],
       [-123.545441, 46.261769],
       [-123.72618, 46.300108],
       [-123.874058, 46.239861],
       [-124.065751, 46.327492],
       [-124.027412, 46.464416],
       [-123.895966, 46.535616],
       [-124.098612, 46.74374],
       [-124.235536, 47.285957],
       [-124.31769, 47.357157],
       [-124.427229, 47.740543],
       [-124.624399, 47.88842],
       [-124.706553, 48.184175],
       [-124.597014, 48.381345],
       [-124.394367, 48.288237],
       [-123.983597, 48.162267],
       [-123.704273, 48.167744],
       [-123.424949, 48.118452],
       [-123.162056, 48.167744],
       [-123.036086, 48.080113],
       [-122.800578, 48.08559],
       [-122.636269, 47.866512],
       [-122.515777, 47.882943],
       [-122.493869, 47.587189],
       [-122.422669, 47.318818],
       [-122.324084, 47.346203],
       [-122.422669, 47.576235],
       [-122.395284, 47.800789],
       [-122.230976, 48.030821],
       [-122.362422, 48.123929],
       [-122.373376, 48.288237],
       [-122.471961, 48.468976],
       [-122.422669, 48.600422],
       [-122.488392, 48.753777],
       [-122.647223, 48.775685],
       [-122.795101, 48.8907],
       [-122.756762, 49.000239],
       [-117.033359, 49.000239]]],
     [[[-122.718423, 48.310145],
       [-122.586977, 48.35396],
       [-122.608885, 48.151313],
       [-122.767716, 48.227991],
       [-122.718423, 48.310145]]],
     [[[-123.025132, 48.583992],
       [-122.915593, 48.715438],
       [-122.767716, 48.556607],
       [-122.811531, 48.419683],
       [-123.041563, 48.458022],
       [-123.025132, 48.583992]]]]}},
  {'type': 'Feature',
   'id': '56',
   'properties': {'name': 'Wyoming', 'density': 5.851},
   'geometry': {'type': 'Polygon',
    'coordinates': [[[-109.080842, 45.002073],
      [-105.91517, 45.002073],
      [-104.058488, 44.996596],
      [-104.053011, 43.002989],
      [-104.053011, 41.003906],
      [-105.728954, 40.998429],
      [-107.919731, 41.003906],
      [-109.04798, 40.998429],
      [-111.047063, 40.998429],
      [-111.047063, 42.000709],
      [-111.047063, 44.476286],
      [-111.05254, 45.002073],
      [-109.080842, 45.002073]]]}}]}

In [37]:
fig = px.choropleth(df, geojson=westgeoj, locations='fips', color='VALUE',
                           color_continuous_scale="orrd",
                           range_color=(396000, 869000),
                           scope="usa",
                           labels={'VALUE':'Avg. Price'}
                          )
fig.update_layout(title="Average House Price In The Western US (Oct. 2024)", title_font_size = 30,
                  font=dict( family="Courier New, monospace", size=25,color="#000000"),
                  template = "ggplot2", hovermode= 'closest', legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01), margin=dict(l=0, r=0, b=0, t=50, pad=0))
fig.update_geos(fitbounds="locations")
pio.write_image(fig, "images/west.png", width=5*300, height=2*300, scale=1.5)
fig.show()

In [38]:
df = pd.read_csv('CSV/Zillow Data/zhvi/State_zhvi_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv')
df.info()
# df.T

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Columns: 304 entries, RegionID to 2024-11-30
dtypes: float64(300), int64(2), object(2)
memory usage: 121.3+ KB

In [39]:
df_rotated = df.T
print(len(df_rotated), len(df_rotated.index))
df_rotated = df_rotated.reset_index(drop=False)
df_rotated = df_rotated.drop([0,1]).reset_index(drop=True)
df_rotated.columns = df_rotated.iloc[0]
df_rotated = df_rotated.drop([0,1,2]).reset_index(drop=True)
df_rotated = df_rotated.rename(columns={'RegionName': 'Date'})
df_rotated

304 304

,Date,California,Texas,Florida,New York,Pennsylvania,Illinois,Ohio,Georgia,North Carolina,...,Maine,Rhode Island,Montana,Delaware,South Dakota,North Dakota,Alaska,District of Columbia,Vermont,Wyoming
0,2000-01-31,188110.256109,110727.473905,106324.231241,151685.625556,96826.092693,125880.837963,103775.989678,122229.145262,126136.015432,...,104793.850333,129534.352773,NaN,145668.725205,106591.506716,NaN,136177.665902,161582.503349,114017.007313,NaN
1,2000-02-29,188742.550827,110787.646075,106554.539424,152225.775385,97033.196372,125981.719743,103839.406222,122506.706514,126327.915075,...,105142.501395,130123.463926,NaN,145895.35231,106365.034979,NaN,136332.334961,162111.004776,114207.925831,NaN
2,2000-03-31,189596.303528,110816.83052,106833.718848,152745.756703,97227.818199,126199.780237,103935.580772,122826.965845,126525.567853,...,105453.802271,130742.127542,NaN,146177.523456,106048.104539,NaN,136486.923129,162860.893805,114507.756737,NaN
3,2000-04-30,191449.546076,110961.675508,107401.218812,153864.095163,97624.427909,126712.764673,104218.386676,123501.252313,126954.311641,...,106139.616024,131964.505895,NaN,146822.842472,105620.916298,NaN,136668.218918,164468.810187,115096.906783,NaN
4,2000-05-31,193603.661365,111055.479394,108013.206369,155021.175699,98031.845388,127321.436742,104649.595355,124244.963429,127431.956046,...,106785.656136,133182.550875,NaN,147558.857533,105443.193507,NaN,136941.145523,166253.299818,115775.371612,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,2024-07-31,770909.700185,300761.659685,393384.745904,471724.29051,262512.871697,262145.854667,225514.071385,326819.452318,326119.092998,...,392414.518193,458019.523326,445990.962084,380615.495815,299744.60848,261044.908554,365349.007564,604323.696478,391769.436874,343370.401509
295,2024-08-31,772682.310069,300348.385031,392375.047571,474811.92333,262759.825236,262952.201015,226092.66836,327004.64373,325920.341852,...,392911.519785,460772.210859,446951.37745,380716.039673,299981.323995,261928.601577,365433.1158,601608.230187,391351.181104,344757.832431
296,2024-09-30,774983.54689,300090.532553,391524.22625,477666.31321,263141.794227,263720.908428,226496.094487,327062.859776,325808.582656,...,393884.425184,463572.005494,448678.957679,381345.642744,300751.524631,262699.506941,365988.556093,601444.565771,390548.180191,347033.423656
297,2024-10-31,776577.716233,299833.86737,390581.313239,480077.616977,263875.785085,264583.245848,226977.257664,326857.936894,325825.649389,...,395025.697955,466022.072369,450714.830573,382659.669353,301863.19549,263619.024608,367221.433345,601349.733091,390142.078284,349781.067684
298,2024-11-30,778354.932718,299466.823298,389387.085235,481903.562884,264751.674429,265510.101009,227606.641522,326280.449977,325799.916366,...,395519.684807,467966.912053,452049.727687,384079.297084,302776.255308,264754.880432,368473.303272,600909.611676,388745.249545,352013.031923

In [40]:
northeast_names = ["Date", "Connecticut", "Maine", "Massachusetts", "New Hampshire", "Rhode Island", "Vermont", "New Jersey", "New York", "Pennsylvania", "Maryland", "Delaware"]
northeast = df_rotated[northeast_names].copy()
northeast['Average'] = northeast.iloc[:, 1:].mean(axis=1)

midwest_names = ["Date", "Illinois", "Indiana", "Iowa", "Kansas", "Michigan", "Minnesota", "Missouri", "Nebraska", "North Dakota", "Ohio", "South Dakota", "Wisconsin"]
midwest = df_rotated[midwest_names].copy()
midwest['Average'] = midwest.iloc[:, 1:].mean(axis=1)

south_names = ["Date", "Alabama", "Arkansas", "Florida", "Georgia", "Kentucky", "Louisiana", "Mississippi", "North Carolina", "Oklahoma", "South Carolina", "Tennessee", "Texas", "Virginia", "West Virginia"]
south = df_rotated[south_names].copy()
south['Average'] = south.iloc[:, 1:].mean(axis=1)

west_names = ["Date", "Alaska", "Arizona", "California", "Colorado", "Idaho", "Montana", "Nevada", "New Mexico", "Oregon", "Utah", "Washington", "Wyoming"]
west = df_rotated[west_names].copy()
west['Average'] = west.iloc[:, 1:].mean(axis=1)

In [41]:
fig = make_subplots(rows=2, cols=2,
                    x_title = 'Time (Months)',
                    y_title = 'Average Price (USD)',
                    subplot_titles=('Northeast', 'Midwest', 'South', 'West'))
fig.update_layout(title="Average Price by Region over Time: 2000 - 2024",
                  font=dict( family="Courier New, monospace", color="#000000", size=15),
                  template = "ggplot2", hovermode= 'closest',)
fig.update_annotations(font_size=20)
fig.update_yaxes(showline=True, linewidth=1, linecolor='gray',title_standoff = 5)

for state in northeast.columns[1:-1]:  # Skipping the first column ('Date')
    fig.add_trace(go.Scatter(x=northeast['Date'], y=northeast[state], line=dict(color=gray), mode='lines', name = state, showlegend=False), row = 1, col = 1)

fig.add_trace(go.Scatter(x=northeast['Date'], y=northeast["Average"], line=dict(color=red), mode='lines', showlegend=False, name="Average"), row = 1, col = 1)

for state in midwest.columns[1:-1]:  # Skipping the first column ('Date')
    fig.add_trace(go.Scatter(x=midwest['Date'], y=midwest[state], line=dict(color=gray), mode='lines', name = state, showlegend=False), row = 1, col = 2)

fig.add_trace(go.Scatter(x=midwest['Date'], y=midwest["Average"], line=dict(color=blue), mode='lines', showlegend=False, name=" "), row = 1, col = 2)

for state in south.columns[1:-1]:  # Skipping the first column ('Date')
    fig.add_trace(go.Scatter(x=south['Date'], y=south[state], line=dict(color=gray), mode='lines', name = state, showlegend=False), row = 2, col = 1)

fig.add_trace(go.Scatter(x=south['Date'], y=south["Average"], line=dict(color=green), mode='lines', showlegend=False, name=" "), row = 2, col = 1)

for state in west.columns[1:-1]:  # Skipping the first column ('Date')
    fig.add_trace(go.Scatter(x=west['Date'], y=west[state], line=dict(color=gray), mode='lines', name = state, showlegend=False), row = 2, col = 2)

fig.add_trace(go.Scatter(x=west['Date'], y=west["Average"], line=dict(color=yellow), mode='lines', showlegend=False, name=" "), row = 2, col = 2)

#
# fig.add_trace(go.Scatter(x = df_rotated['Date'], y = df_rotated['California'], mode = 'lines',
#                          name = 'Days To Pending', line=dict(color=red, width=4), showlegend=True))
pio.write_image(fig, "images/price_by_region.png", width=5*300, height=2*300, scale=1.5)

fig

In [42]:
medhi = pd.read_csv('CSV/Median Household Income/MEHOINUSA646N.csv')

medhi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   observation_date  40 non-null     object
 1   MEHOINUSA646N     40 non-null     int64
dtypes: int64(1), object(1)
memory usage: 772.0+ bytes

In [43]:
fig = go.Figure()
fig.update_layout(title="Median US Household Income: 1984 - 2023", title_font_size = 30,
                  font=dict( family="Courier New, monospace", size=25,color="#000000"),
                  template = "ggplot2", hovermode= 'closest', legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01))
fig.update_xaxes(showline=True, linewidth=2, linecolor='gray', title="Time (Months)")
fig.update_yaxes(showline=True, linewidth=2, linecolor='gray', title="Days To Pending")

fig.add_trace(go.Scatter(x = medhi['observation_date'], y = medhi['MEHOINUSA646N'], mode = 'lines',
                         name = 'Days To Pending', line=dict(color=red, width=4), showlegend=True))

fig

In [44]:
reg_df

           DATE     MSPUS  year   real_dollars  item_id
0    1963-01-01   17800.0  1963  177244.954248        0
1    1963-04-01   18000.0  1963  179236.470588        1
2    1963-07-01   17900.0  1963  178240.712418        2
3    1963-10-01   18500.0  1963  184215.261438        3
4    1964-01-01   18500.0  1964  181838.290323        4
..          ...       ...   ...            ...      ...
239  2022-10-01  442600.0  2022  460819.412619      239
240  2023-01-01  429000.0  2023  429000.000000      240
241  2023-04-01  418500.0  2023  418500.000000      241
242  2023-07-01  435400.0  2023  435400.000000      242
243  2023-10-01  423200.0  2023  423200.000000      243

[244 rows x 5 columns]

In [45]:
a = reg_df.copy()
a['DATE'] = pd.to_datetime(a['DATE'])
a['year'] = a['DATE'].dt.year
annual_avg = a.groupby('year')['real_dollars'].mean()
a = pd.DataFrame(annual_avg)
a = a.reset_index()
a

    year   real_dollars
0   1963  179734.349673
1   1964  186015.656452
2   1965  194670.722222
3   1966  202194.228395
4   1967  207544.026946
..   ...            ...
56  2019  381686.460766
57  2020  386335.825371
58  2021  430678.178396
59  2022  450772.175087
60  2023  426525.000000

[61 rows x 2 columns]

In [46]:
medhi['observation_date'] = pd.to_datetime(medhi['observation_date'])
medhi['year'] = medhi['observation_date'].dt.year

In [47]:
start_yr = max(medhi['year'].min(), a['year'].min())
end_yr = min(medhi['year'].max(), a['year'].max())

medhi1 = medhi[(medhi['year'] >= start_yr) & (medhi['year'] <= end_yr)]
a1 = a[(a['year'] >= start_yr) & (a['year'] <= end_yr)]

coMHIandHousePrice = pd.merge(medhi1, a1, on='year', how = 'inner')
coMHIandHousePrice = coMHIandHousePrice.drop(['observation_date', 'year'], axis = 1)
coMHIandHousePrice = coMHIandHousePrice.sort_values(by=['MEHOINUSA646N'], ascending=True)
coMHIandHousePrice

    MEHOINUSA646N   real_dollars
0           22420  234465.109721
1           23620  238650.195632
2           24900  255841.255018
3           26060  280830.100352
4           27230  289054.792477
5           28910  295917.244758
6           29940  285119.009946
7           30130  268403.982746
8           30640  263600.892730
9           31240  266746.041522
10          32260  268156.264170
11          34080  266864.169619
12          35490  272367.466539
13          37010  275275.950156
14          38890  283999.088037
15          40700  292859.590336
16          41990  296473.984321
17          42230  297819.967250
18          42410  315076.095331
19          43320  318156.911685
20          44330  351883.225516
21          46330  369059.181260
22          48200  368408.296131
26          49280  311191.324247
25          49780  306282.768474
27          50050  304649.170664
23          50230  359969.301444
24          50300  324864.698123
28          51020  324351.545772
29          53590  348215.722000
30          53660  367819.909308
31          56520  378150.484142
32          59040  387372.858917
33          61140  400797.741310
34          63180  394700.040421
36          68010  386335.825371
35          68700  381686.460766
37          70780  430678.178396
38          74580  450772.175087
39          80610  426525.000000

In [48]:
fig = go.Figure()
fig.update_layout(title="Median US Household Income vs Home Price: 1984 - 2023", title_font_size=30,
                  font=dict(family="Courier New, monospace", size=25, color="#000000"),
                  template="ggplot2", hovermode='closest', legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01))
fig.update_xaxes(showline=True, linewidth=2, linecolor='gray', title="Median Household Income (USD)")
fig.update_yaxes(showline=True, linewidth=2, linecolor='gray', title="Home Price (USD)")

fig.add_trace(go.Scatter(x=coMHIandHousePrice['MEHOINUSA646N'], y=coMHIandHousePrice['real_dollars'], mode='markers',
                         name='Days To Pending', marker=dict(color=red), showlegend=False))

####     REGRESSION     ####

X = coMHIandHousePrice['MEHOINUSA646N']
y = coMHIandHousePrice['real_dollars']
model = LinRegress(X, y)
yy= linear_func(X, *model._results.params)


fig.add_trace(go.Scatter(x = coMHIandHousePrice['MEHOINUSA646N'], y = yy, mode = 'lines',
                         name = 'Regression',
                         line=dict(dash='dash', width=3),marker_color=light_red))

pio.write_image(fig, "images/medvshomeprice.png", width=5*300, height=2*300, scale=1.5)
fig

In [49]:
X = coMHIandHousePrice['MEHOINUSA646N']
y = coMHIandHousePrice['real_dollars']
model = LinRegress(X, y)

b,m = model._results.params
r = model.rsquared
t = model._results.tvalues[1]

print("Med. US Income vs. Home Price:")
print(f"y = {m}*x+{b}")
print(f"R² = {r}")
print(f"t = {t}")

Med. US Income vs. Home Price:
y = 3.4863067101112772*x+165485.38039013295
R² = 0.8672516204868975
t = 15.756136848561466

In [50]:
emratio = pd.read_csv('CSV/EMRATIO/EMRATIO.csv')
emratio['observation_date'] = pd.to_datetime(emratio['observation_date'])
emratio['year'] = emratio['observation_date'].dt.year
annual_avg = emratio.groupby('year')['EMRATIO'].mean()
emratio = pd.DataFrame(annual_avg)
emratio = emratio.reset_index()
emratio

    year    EMRATIO
0   1948  56.616667
1   1949  55.475000
2   1950  56.091667
3   1951  57.316667
4   1952  57.283333
..   ...        ...
72  2020  56.766667
73  2021  58.366667
74  2022  59.966667
75  2023  60.316667
76  2024  60.066667

[77 rows x 2 columns]

In [51]:
start_yr = max(emratio['year'].min(), a['year'].min())
end_yr = min(emratio['year'].max(), a['year'].max())

emratio = emratio[(emratio['year'] >= start_yr) & (emratio['year'] <= end_yr)]
a2 = a[(a['year'] >= start_yr) & (a['year'] <= end_yr)]

emratio_plt = pd.merge(emratio, a2, on='year', how = 'inner')
emratio_plt = emratio_plt.sort_values(by=['EMRATIO'], ascending=True)
emratio_plt = emratio_plt.reset_index()
emratio_plt

    index  year    EMRATIO   real_dollars
0       0  1963  55.350000  179734.349673
1       1  1964  55.666667  186015.656452
2      12  1975  56.050000  222438.123606
3       2  1965  56.166667  194670.722222
4       8  1971  56.591667  189780.443210
..    ...   ...        ...            ...
56     38  2001  63.666667  297819.967250
57     34  1997  63.775000  275275.950156
58     35  1998  64.075000  283999.088037
59     36  1999  64.266667  292859.590336
60     37  2000  64.408333  296473.984321

[61 rows x 4 columns]

In [52]:
fig = go.Figure()
fig.update_layout(title="US Employment Ratio vs. Average House Price: 1963 - 2023", title_font_size = 30,
                  font=dict( family="Courier New, monospace", size=25,color="#000000"),
                  template = "ggplot2", hovermode= 'closest', legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01))
fig.update_xaxes(showline=True, linewidth=2, linecolor='gray', title='Employment Ratio')
fig.update_yaxes(showline=True, linewidth=2, linecolor='gray', title='Average House Price (USD)')

fig.add_trace(go.Scatter(x = emratio_plt['EMRATIO'], y = emratio_plt['real_dollars'], mode = 'markers',
                         marker = dict(color = red), showlegend=False))

####     REGRESSION     ####

X = emratio_plt['EMRATIO']
y = emratio_plt['real_dollars']
model = LinRegress(X, y)
yy= linear_func(X, *model._results.params)


fig.add_trace(go.Scatter(x = emratio_plt['EMRATIO'], y = yy, mode = 'lines',
                         name = 'Regression',
                         line=dict(dash='dash', width=3),marker_color=light_red))

pio.write_image(fig, "images/empratiovshomeprice.png", width=5*300, height=2*300, scale=1.5)
fig

In [53]:
X = emratio_plt['EMRATIO']
y = emratio_plt['real_dollars']
model = LinRegress(X, y)

b,m = model._results.params
r = model.rsquared
t = model._results.tvalues[1]

print("US Employment Ratio vs. Home Price:")
print(f"y = {m}*x+{b}")
print(f"R² = {r}")
print(f"t = {t}")

US Employment Ratio vs. Home Price:
y = 11327.174669164804*x+-392091.182931017
R² = 0.16589028227067215
t = 3.4255072293604685

In [54]:
df = pd.read_csv('CSV/Zillow Data/homeowner income needed/Metro_new_homeowner_income_needed_downpayment_0.20_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv')

df=df.iloc[:1] # Select only US
df = df.drop(['RegionID', 'SizeRank', 'RegionType', 'StateName'], axis=1) # Drop irrelevant columns
df = df.T # Flip it so it's not horizontal
df = df.iloc[1:] # remove top column stuff
df['Index'] = range(1, len(df)+1)

df = df.drop(['Index'], axis=1)
df = df.reset_index()

df = df.set_axis(['DATE', 'INCOME'], axis = 1)

min_income = df
min_income

           DATE        INCOME
0    2012-01-31  36505.939619
1    2012-02-29  36438.092425
2    2012-03-31  36673.913892
3    2012-04-30  36630.661654
4    2012-05-31  36409.259134
..          ...           ...
151  2024-08-31  93685.604529
152  2024-09-30  91666.145567
153  2024-10-31   93646.87737
154  2024-11-30  96607.950522
155  2024-12-31  96105.603497

[156 rows x 2 columns]

In [55]:
fig = go.Figure()
fig.update_layout(title="Minimum Required Salary to Afford a House: Monthly 2012 - 2024", title_font_size = 30,
                  font=dict( family="Courier New, monospace", size=25,color="#000000"),
                  template = "ggplot2", hovermode= 'closest', legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01))
fig.update_xaxes(showline=True, linewidth=2, linecolor='gray', title="Time (Months)")
fig.update_yaxes(showline=True, linewidth=2, linecolor='gray', title="Minimum Required Salary (USD)")

fig.add_trace(go.Scatter(x = min_income['DATE'], y = min_income['INCOME'], mode = 'lines',
                         name = 'Min. Required', line=dict(color=red, width=4), showlegend=True))

fig

In [56]:
reg_df

           DATE     MSPUS  year   real_dollars  item_id
0    1963-01-01   17800.0  1963  177244.954248        0
1    1963-04-01   18000.0  1963  179236.470588        1
2    1963-07-01   17900.0  1963  178240.712418        2
3    1963-10-01   18500.0  1963  184215.261438        3
4    1964-01-01   18500.0  1964  181838.290323        4
..          ...       ...   ...            ...      ...
239  2022-10-01  442600.0  2022  460819.412619      239
240  2023-01-01  429000.0  2023  429000.000000      240
241  2023-04-01  418500.0  2023  418500.000000      241
242  2023-07-01  435400.0  2023  435400.000000      242
243  2023-10-01  423200.0  2023  423200.000000      243

[244 rows x 5 columns]

In [57]:
min_income['DATE'] = pd.to_datetime(min_income['DATE'])
reg_df['DATE'] = pd.to_datetime(reg_df['DATE'])

start_yr = max(min_income['DATE'].min(), reg_df['DATE'].min())
end_yr = min(min_income['DATE'].max(), reg_df['DATE'].max())

min_income = min_income[(min_income['DATE'] >= start_yr) & (min_income['DATE'] <= end_yr)]
reg_df1 = reg_df[(reg_df['DATE'] >= start_yr) & (reg_df['DATE'] <= end_yr)]
reg_df1 = reg_df1.reset_index(drop=True)

min_income['DATE'] = min_income['DATE'].dt.to_period('M').dt.to_timestamp()
mi_plt = pd.merge(min_income, reg_df1, on='DATE', how = 'inner')
mi_plt = mi_plt.sort_values(by=['INCOME'], ascending=True)
mi_plt = mi_plt.reset_index(drop=True)
mi_plt['INCOME']=mi_plt['INCOME'].astype(float)
mi_plt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46 entries, 0 to 45
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   DATE          46 non-null     datetime64[ns]
 1   INCOME        46 non-null     float64
 2   MSPUS         46 non-null     float64
 3   year          46 non-null     Int64
 4   real_dollars  46 non-null     float64
 5   item_id       46 non-null     int64
dtypes: Int64(1), datetime64[ns](1), float64(3), int64(1)
memory usage: 2.3 KB

/tmp/ipykernel_88593/3237024179.py:11: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [58]:
fig = go.Figure()
fig.update_layout(title="Average House Price vs. US Minimum Salary: 2012 - 2023 (Monthly)", title_font_size = 30,
                  font=dict( family="Courier New, monospace", size=25,color="#000000"),
                  template = "ggplot2", hovermode= 'closest', legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01))
fig.update_xaxes(showline=True, linewidth=2, linecolor='gray', title='Mean House Price (USD)')
fig.update_yaxes(showline=True, linewidth=2, linecolor='gray', title='Minimum Income (USD)')

fig.add_trace(go.Scatter(x = mi_plt['real_dollars'], y = mi_plt['INCOME'], mode = 'markers',
                         marker = dict(color = red), showlegend=False))

####     REGRESSION     ####

X = mi_plt['real_dollars']
y = mi_plt['INCOME']
model = LinRegress(X, y)
yy= linear_func(X, *model._results.params)


fig.add_trace(go.Scatter(x = mi_plt['real_dollars'], y = yy, mode = 'lines',
                         name = 'Regression',
                         line=dict(dash='dash', width=3),marker_color=light_red))

pio.write_image(fig, "images/houseprvsusminsal2012-2023.png", width=5*300, height=2*300, scale=1.5)
fig

In [59]:

X = mi_plt['real_dollars']
y = mi_plt['INCOME']
model = LinRegress(X, y)

b,m = model._results.params
r = model.rsquared
t = model._results.tvalues[1]

print("House Price vs. Min Income:")
print(f"y = {m}*x+{b}")
print(f"R² = {r}")
print(f"t = {t}")

House Price vs. Min Income:
y = 0.3444242312225833*x+-82739.5725732185
R² = 0.6347919730964326
t = 8.745243257895142

In [60]:
racedata = pd.read_csv("CSV/Zillow Data/Home Ownership Price by Race.csv")
racedata

               Race  Property Cost
0             Asian         473836
1             Black         196891
2        Indigenous         212812
3          Hispanic         267686
4             White         254655
5  Pacific Islander         385903

In [62]:
fig = px.bar(racedata, x = 'Race', y = 'Property Cost', color='Property Cost', color_continuous_scale=px.colors.sequential.Sunsetdark)

fig.update_layout(title="Average House Ownership Price by Race: 2020", title_font_size = 30,
                  font=dict( family="Courier New, monospace", size=25,color="#000000"),
                  template = "ggplot2", hovermode= 'closest', legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01))
fig.update_xaxes(showline=True, linewidth=2, linecolor='gray', title='Race')
fig.update_yaxes(showline=True, linewidth=2, linecolor='gray', title='Mean Owned House Price (USD)')

pio.write_image(fig, "images/race.png", width=5*300, height=2*300, scale=1.5)
fig